# Generated by Django 5.1.6 on 2025-05-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_remove_article_gallery_images_galleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
