# Generated by Django 5.1.6 on 2025-05-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_author_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.TextField(null=True),
        ),
    ]
