# Generated by Django 5.1.6 on 2025-05-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_comment_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_image',
            field=models.ImageField(null=True, upload_to='forum:images/'),
        ),
    ]
