# Generated by Django 5.1.6 on 2025-05-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Thread',
        ),
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='ThreadCategory',
        ),
    ]
