# Generated by Django 5.1.6 on 2025-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_thread_thread_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
