# Generated by Django 5.1.6 on 2025-05-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_thread_thread_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread_image',
            new_name='image',
        ),
    ]
