# Generated by Django 5.1.6 on 2025-05-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_product_merch_image_alter_product_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='merch_image',
            field=models.ImageField(blank=True, null=True, upload_to='merchstore/'),
        ),
    ]
