# Generated by Django 5.1.6 on 2025-05-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0005_product_sale_alter_product_merch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
