# Generated by Django 5.1.6 on 2025-05-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0006_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, default=models.DecimalField(decimal_places=2, max_digits=10), null=True),
        ),
    ]
