# Generated by Django 5.1.6 on 2025-05-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0008_alter_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='sale_percent',
        ),
    ]
