# Generated by Django 5.1.6 on 2025-05-13 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0009_rename_sale_product_sale_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=10), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
