# Generated by Django 5.1.6 on 2025-05-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_alter_product_owner_alter_transaction_buyer_and_more'),
        ('merchstore', '0010_alter_product_sale_price'),
    ]

    operations = [
    ]
