# Generated by Django 5.1.6 on 2025-05-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0012_alter_product_sale_percent_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='merch_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/merchstore/'),
        ),
    ]
