# Generated by Django 5.1.6 on 2025-03-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_comment_options_alter_comment_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-UpdatedOn']},
        ),
    ]
