# Generated by Django 5.1.6 on 2025-05-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_alter_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='peopleRequired',
        ),
    ]
