# Generated by Django 5.1.6 on 2025-05-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_commission_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
