# Generated by Django 5.1.6 on 2025-05-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0016_alter_commission_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={},
        ),
    ]
