# Generated by Django 5.1.6 on 2025-05-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0017_alter_jobapplication_options'),
        ('user_management', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='createdOn',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='updatedOn',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='createdOn',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='manpowerRequired',
            new_name='manpower_required',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='appliedOn',
            new_name='applied_on',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='commissions.job'),
        ),
    ]
