# Generated by Django 5.1.6 on 2025-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_article_header_image_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery_images',
            field=models.ImageField(blank=True, null=True, upload_to='wiki/'),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
