<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-05-14 15:11
=======
# Generated by Django 5.1.6 on 2025-05-14 16:45
>>>>>>> master

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
