# Generated by Django 5.1.6 on 2025-05-03 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_alter_job_options_remove_job_updatedon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commissions.commission'),
        ),
    ]
