# Generated by Django 5.1.6 on 2025-05-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0014_alter_commission_options_alter_commission_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-appliedOn']},
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='CreatedOn',
            new_name='createdOn',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='UpdatedOn',
            new_name='updatedOn',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='CreatedOn',
            new_name='createdOn',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='AppliedOn',
            new_name='appliedOn',
        ),
    ]
